###
GET http://localhost:3001/api/persons
###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "asas",
    "number": "32322323233323434"
}
###
GET http://localhost:3001/api/persons/62d9b2ea29dc85747562c0c4
###
DELETE http://localhost:3001/api/persons/62daa2191ccbb886c4f3fd3f
###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "uwu",
    "number": "223334455"
}